### PR TITLE
fix: cleanup eslint warnings

### LINKED ISSUE #567: Clean up eslint warnings
- [ ] FIx eslint warnings
- [ ] decide to set those rules from `warning` to `error` (for example unused imports)

### PR DESCRIPTION
**Pull request by YohannesTesfay**
Closes #567

### CODE REVIEW

File: packages/ui/src/spinner.tsx [hunk 1]
```diff
@@ -11,10 +11,5 @@ interface SpinnerProps {
 }
 
 export const Spinner = ({ size }: SpinnerProps): JSX.Element => {
-  return (
-    <CgSpinner
-      size={size ? Size[size] : Size.small}
-      className="text-black-600 inline  animate-spin dark:text-blue-600"
-    />
-  )
+  return <CgSpinner size={size ? Size[size] : Size.small} className="inline  animate-spin dark:text-blue-600" />
```
Comment (PascalHelbig) [inline packages/ui/src/spinner.tsx:14]:
```suggestion
  return <CgSpinner size={size ? Size[size] : Size.small} className="inline animate-spin dark:text-blue-600" />
```

File: packages/ui/src/table/table.tsx [hunk 2]
```diff
@@ -17,9 +17,7 @@ export const TableHeadRow: React.FC<DefaultTableComponentProps> = ({ children, c
 
 export const TableHeadCell: React.FC<DefaultTableComponentProps> = ({ children, className = '' }) => {
   return (
-    <th
-      className={`border-b bg-gray-100 px-2 pb-2 pt-2 text-left text-gray-600 dark:bg-slate-800  dark:text-white ${className}`}
-    >
+    <th className={`border-b bg-gray-100 p-2 text-left text-gray-600 dark:bg-slate-800 dark:text-white${className}`}>
```
Comment (PascalHelbig) [inline packages/ui/src/table/table.tsx:20]:
```suggestion
    <th className={`border-b bg-gray-100 p-2 text-left text-gray-600 dark:bg-slate-800 dark:text-white ${className}`}>
```

**Review by PascalHelbig — APPROVED** [review]
Looks good to me!
Just two tiny comments:
